### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by najdovski-stef** [Kronka/miniapp#2]
I successfully compiled it with VS19 Community, I have a few questions,
What is the license of this Demo project?
Can I use it as a base for my own app?
Is there a way to compile to newer SDK and for ARMv8?

**Comment by Kronka** [comment]
I'm sorry that I didn't answer for a long time, because I didn't see it.
The license of this project is the GNU General Public License
This is my first repository, I forgot to sign GNU.
debugging -> options -> cross-platform -> C++ -> Android
you need to change the path to last version of the SDK
About ARMv8 - I do not know

**Comment by VadimBoev** [comment]
> I successfully compiled it with VS19 Community, I have a few questions,
> What is the license of this Demo project?
> Can I use it as a base for my own app?
> Is there a way to compile to newer SDK and for ARMv8?

I'm sorry that I didn't answer for a long time, because I didn't see it.
The license of this project is the GNU General Public License
This is my first repository, I forgot to sign GNU.
As for the SDK, I can say yes.
This is done in: debugging -> options -> cross-platform -> C++ -> Android
you need to change the path to last version of the SDK
About ARMv8 - as far as I know, ARMv8 is ARM64-v8a, select ARM64 in the project and configure it, it should work

**Comment by najdovski-stef** [comment]
> > I successfully compiled it with VS19 Community, I have a few questions,
> > What is the license of this Demo project?
> > Can I use it as a base for my own app?
> > Is there a way to compile to newer SDK and for ARMv8?
> 
> I'm sorry that I didn't answer for a long time, because I didn't see it. The license of this project is the GNU General Public License This is my first repository, I forgot to sign GNU. As for the SDK, I can say yes. This is done in: debugging -> options -> cross-platform -> C++ -> Android you need to change the path to last version of the SDK About ARMv8 - as far as I know, ARMv8 is ARM64-v8a, select ARM64 in the project and configure it, it should work

Thank You, Its allright, I wanted to use this demo as a start for my project, I am happy that the license is GNU General Public License, I will credit you in about for sure!, if I get to the level of publishing, and my project will be probably open source. Thank you again. Good Luck with your projects!
